/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PermitCallee, PermitCalleeInterface } from "../PermitCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "callFunction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102b2806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80639c23da5014610030575b600080fd5b61004361003e366004610175565b610045565b005b6000806000806000806000808880602001905181019061006591906100eb565b97509750975097509750975097509750876001600160a01b031663d505accf888888888888886040518863ffffffff1660e01b81526004016100ad9796959493929190610223565b600060405180830381600087803b1580156100c757600080fd5b505af11580156100db573d6000803e3d6000fd5b5050505050505050505050505050565b600080600080600080600080610100898b031215610107578384fd5b885161011281610264565b60208a015190985061012381610264565b60408a015190975061013481610264565b80965050606089015194506080890151935060a089015160ff81168114610159578384fd5b60c08a015160e0909a0151989b979a5095989497939692505050565b60008060408385031215610187578182fd5b823561019281610264565b915060208381013567ffffffffffffffff808211156101af578384fd5b81860187601f8201126101c0578485fd5b80359250818311156101d0578485fd5b604051601f8401601f19168101850183811182821017156101ef578687fd5b6040528381528184018501891015610205578586fd5b83858301868301378585858301015280955050505050509250929050565b6001600160a01b0397881681529590961660208601526040850193909352606084019190915260ff16608083015260a082015260c081019190915260e00190565b6001600160a01b038116811461027957600080fd5b5056fea26469706673582212207c9296f957e860d47b0c2616861ea5d74c2b4db6baf430f48615bc5524096a9064736f6c634300060a0033";

type PermitCalleeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PermitCalleeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PermitCallee__factory extends ContractFactory {
  constructor(...args: PermitCalleeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "PermitCallee";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PermitCallee> {
    return super.deploy(overrides || {}) as Promise<PermitCallee>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PermitCallee {
    return super.attach(address) as PermitCallee;
  }
  connect(signer: Signer): PermitCallee__factory {
    return super.connect(signer) as PermitCallee__factory;
  }
  static readonly contractName: "PermitCallee";
  public readonly contractName: "PermitCallee";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PermitCalleeInterface {
    return new utils.Interface(_abi) as PermitCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PermitCallee {
    return new Contract(address, _abi, signerOrProvider) as PermitCallee;
  }
}
