/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  UpgradeableContractV1,
  UpgradeableContractV1Interface,
} from "../UpgradeableContractV1";

const _abi = [
  {
    inputs: [],
    name: "addressBook",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getV1Version",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addressBook",
        type: "address",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610228806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063485cc955146100515780638da5cb5b146100815780638f26c061146100a5578063f5887cdd146100bf575b600080fd5b61007f6004803603604081101561006757600080fd5b506001600160a01b03813581169160200135166100c7565b005b61008961019b565b604080516001600160a01b039092168252519081900360200190f35b6100ad6101aa565b60408051918252519081900360200190f35b6100896101af565b600054610100900460ff16806100e057506100e06101be565b806100ee575060005460ff16155b6101295760405162461bcd60e51b815260040180806020018281038252602e8152602001806101c5602e913960400191505060405180910390fd5b600054610100900460ff16158015610154576000805460ff1961ff0019909116610100171660011790555b603380546001600160a01b038086166001600160a01b03199283161790925560348054928516929091169190911790558015610196576000805461ff00191690555b505050565b6034546001600160a01b031681565b600190565b6033546001600160a01b031681565b303b159056fe436f6e747261637420696e7374616e63652068617320616c7265616479206265656e20696e697469616c697a6564a26469706673582212202c44165c9926c16b0d62eb343525ced56dc43ee914ee10a23b11e76d51ea010864736f6c634300060a0033";

type UpgradeableContractV1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UpgradeableContractV1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UpgradeableContractV1__factory extends ContractFactory {
  constructor(...args: UpgradeableContractV1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "UpgradeableContractV1";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<UpgradeableContractV1> {
    return super.deploy(overrides || {}) as Promise<UpgradeableContractV1>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): UpgradeableContractV1 {
    return super.attach(address) as UpgradeableContractV1;
  }
  connect(signer: Signer): UpgradeableContractV1__factory {
    return super.connect(signer) as UpgradeableContractV1__factory;
  }
  static readonly contractName: "UpgradeableContractV1";
  public readonly contractName: "UpgradeableContractV1";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UpgradeableContractV1Interface {
    return new utils.Interface(_abi) as UpgradeableContractV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UpgradeableContractV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as UpgradeableContractV1;
  }
}
