/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace MarginVault {
  export type VaultStruct = {
    shortOtokens: string[];
    longOtokens: string[];
    collateralAssets: string[];
    shortAmounts: BigNumberish[];
    longAmounts: BigNumberish[];
    collateralAmounts: BigNumberish[];
  };

  export type VaultStructOutput = [
    string[],
    string[],
    string[],
    BigNumber[],
    BigNumber[],
    BigNumber[]
  ] & {
    shortOtokens: string[];
    longOtokens: string[];
    collateralAssets: string[];
    shortAmounts: BigNumber[];
    longAmounts: BigNumber[];
    collateralAmounts: BigNumber[];
  };
}

export declare namespace Actions {
  export type ActionArgsStruct = {
    actionType: BigNumberish;
    owner: string;
    secondAddress: string;
    asset: string;
    vaultId: BigNumberish;
    amount: BigNumberish;
    index: BigNumberish;
    data: BytesLike;
  };

  export type ActionArgsStructOutput = [
    number,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    actionType: number;
    owner: string;
    secondAddress: string;
    asset: string;
    vaultId: BigNumber;
    amount: BigNumber;
    index: BigNumber;
    data: string;
  };
}

export interface ControllerInterface extends utils.Interface {
  contractName: "Controller";
  functions: {
    "addressbook()": FunctionFragment;
    "calculator()": FunctionFragment;
    "callRestricted()": FunctionFragment;
    "canSettleAssets(address,address,address,uint256)": FunctionFragment;
    "donate(address,uint256)": FunctionFragment;
    "fullPauser()": FunctionFragment;
    "getAccountVaultCounter(address)": FunctionFragment;
    "getConfiguration()": FunctionFragment;
    "getNakedCap(address)": FunctionFragment;
    "getNakedPoolBalance(address)": FunctionFragment;
    "getPayout(address,uint256)": FunctionFragment;
    "getProceed(address,uint256)": FunctionFragment;
    "getVault(address,uint256)": FunctionFragment;
    "getVaultWithDetails(address,uint256)": FunctionFragment;
    "hasExpired(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "isLiquidatable(address,uint256,uint256)": FunctionFragment;
    "isOperator(address,address)": FunctionFragment;
    "isSettlementAllowed(address)": FunctionFragment;
    "operate((uint8,address,address,address,uint256,uint256,uint256,bytes)[])": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "partialPauser()": FunctionFragment;
    "pool()": FunctionFragment;
    "refreshConfiguration()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCallRestriction(bool)": FunctionFragment;
    "setFullPauser(address)": FunctionFragment;
    "setNakedCap(address,uint256)": FunctionFragment;
    "setOperator(address,bool)": FunctionFragment;
    "setPartialPauser(address)": FunctionFragment;
    "setSystemFullyPaused(bool)": FunctionFragment;
    "setSystemPartiallyPaused(bool)": FunctionFragment;
    "sync(address,uint256)": FunctionFragment;
    "systemFullyPaused()": FunctionFragment;
    "systemPartiallyPaused()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelist()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressbook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callRestricted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canSettleAssets",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fullPauser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountVaultCounter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getNakedCap", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getNakedPoolBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayout",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProceed",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultWithDetails",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hasExpired", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isLiquidatable",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isSettlementAllowed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "operate",
    values: [Actions.ActionArgsStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partialPauser",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refreshConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCallRestriction",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFullPauser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setNakedCap",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPartialPauser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSystemFullyPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSystemPartiallyPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sync",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "systemFullyPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "systemPartiallyPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "whitelist", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addressbook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "calculator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canSettleAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fullPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccountVaultCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNakedCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNakedPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProceed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultWithDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLiquidatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSettlementAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "partialPauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refreshConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCallRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFullPauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNakedCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPartialPauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSystemFullyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSystemPartiallyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sync", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "systemFullyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemPartiallyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;

  events: {
    "AccountOperatorUpdated(address,address,bool)": EventFragment;
    "CallExecuted(address,address,bytes)": EventFragment;
    "CallRestricted(bool)": EventFragment;
    "CollateralAssetDeposited(address,address,address,uint256,uint256)": EventFragment;
    "CollateralAssetWithdrawed(address,address,address,uint256,uint256)": EventFragment;
    "Donated(address,address,uint256)": EventFragment;
    "FullPauserUpdated(address,address)": EventFragment;
    "LongOtokenDeposited(address,address,address,uint256,uint256)": EventFragment;
    "LongOtokenWithdrawed(address,address,address,uint256,uint256)": EventFragment;
    "NakedCapUpdated(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PartialPauserUpdated(address,address)": EventFragment;
    "Redeem(address,address,address,address,uint256,uint256)": EventFragment;
    "ShortOtokenBurned(address,address,address,uint256,uint256)": EventFragment;
    "ShortOtokenMinted(address,address,address,uint256,uint256)": EventFragment;
    "SystemFullyPaused(bool)": EventFragment;
    "SystemPartiallyPaused(bool)": EventFragment;
    "VaultLiquidated(address,address,address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "VaultOpened(address,uint256,uint256)": EventFragment;
    "VaultSettled(address,address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountOperatorUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CallExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CallRestricted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollateralAssetDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollateralAssetWithdrawed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Donated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FullPauserUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LongOtokenDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LongOtokenWithdrawed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NakedCapUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PartialPauserUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeem"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShortOtokenBurned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShortOtokenMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SystemFullyPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SystemPartiallyPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultLiquidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultOpened"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultSettled"): EventFragment;
}

export type AccountOperatorUpdatedEvent = TypedEvent<
  [string, string, boolean],
  { accountOwner: string; operator: string; isSet: boolean }
>;

export type AccountOperatorUpdatedEventFilter =
  TypedEventFilter<AccountOperatorUpdatedEvent>;

export type CallExecutedEvent = TypedEvent<
  [string, string, string],
  { from: string; to: string; data: string }
>;

export type CallExecutedEventFilter = TypedEventFilter<CallExecutedEvent>;

export type CallRestrictedEvent = TypedEvent<
  [boolean],
  { isRestricted: boolean }
>;

export type CallRestrictedEventFilter = TypedEventFilter<CallRestrictedEvent>;

export type CollateralAssetDepositedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  {
    asset: string;
    accountOwner: string;
    from: string;
    vaultId: BigNumber;
    amount: BigNumber;
  }
>;

export type CollateralAssetDepositedEventFilter =
  TypedEventFilter<CollateralAssetDepositedEvent>;

export type CollateralAssetWithdrawedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  {
    asset: string;
    AccountOwner: string;
    to: string;
    vaultId: BigNumber;
    amount: BigNumber;
  }
>;

export type CollateralAssetWithdrawedEventFilter =
  TypedEventFilter<CollateralAssetWithdrawedEvent>;

export type DonatedEvent = TypedEvent<
  [string, string, BigNumber],
  { donator: string; asset: string; amount: BigNumber }
>;

export type DonatedEventFilter = TypedEventFilter<DonatedEvent>;

export type FullPauserUpdatedEvent = TypedEvent<
  [string, string],
  { oldFullPauser: string; newFullPauser: string }
>;

export type FullPauserUpdatedEventFilter =
  TypedEventFilter<FullPauserUpdatedEvent>;

export type LongOtokenDepositedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  {
    otoken: string;
    accountOwner: string;
    from: string;
    vaultId: BigNumber;
    amount: BigNumber;
  }
>;

export type LongOtokenDepositedEventFilter =
  TypedEventFilter<LongOtokenDepositedEvent>;

export type LongOtokenWithdrawedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  {
    otoken: string;
    AccountOwner: string;
    to: string;
    vaultId: BigNumber;
    amount: BigNumber;
  }
>;

export type LongOtokenWithdrawedEventFilter =
  TypedEventFilter<LongOtokenWithdrawedEvent>;

export type NakedCapUpdatedEvent = TypedEvent<
  [string, BigNumber],
  { collateral: string; cap: BigNumber }
>;

export type NakedCapUpdatedEventFilter = TypedEventFilter<NakedCapUpdatedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type PartialPauserUpdatedEvent = TypedEvent<
  [string, string],
  { oldPartialPauser: string; newPartialPauser: string }
>;

export type PartialPauserUpdatedEventFilter =
  TypedEventFilter<PartialPauserUpdatedEvent>;

export type RedeemEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber],
  {
    otoken: string;
    redeemer: string;
    receiver: string;
    collateralAsset: string;
    otokenBurned: BigNumber;
    payout: BigNumber;
  }
>;

export type RedeemEventFilter = TypedEventFilter<RedeemEvent>;

export type ShortOtokenBurnedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  {
    otoken: string;
    AccountOwner: string;
    from: string;
    vaultId: BigNumber;
    amount: BigNumber;
  }
>;

export type ShortOtokenBurnedEventFilter =
  TypedEventFilter<ShortOtokenBurnedEvent>;

export type ShortOtokenMintedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  {
    otoken: string;
    AccountOwner: string;
    to: string;
    vaultId: BigNumber;
    amount: BigNumber;
  }
>;

export type ShortOtokenMintedEventFilter =
  TypedEventFilter<ShortOtokenMintedEvent>;

export type SystemFullyPausedEvent = TypedEvent<
  [boolean],
  { isPaused: boolean }
>;

export type SystemFullyPausedEventFilter =
  TypedEventFilter<SystemFullyPausedEvent>;

export type SystemPartiallyPausedEvent = TypedEvent<
  [boolean],
  { isPaused: boolean }
>;

export type SystemPartiallyPausedEventFilter =
  TypedEventFilter<SystemPartiallyPausedEvent>;

export type VaultLiquidatedEvent = TypedEvent<
  [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  {
    liquidator: string;
    receiver: string;
    vaultOwner: string;
    auctionPrice: BigNumber;
    auctionStartingRound: BigNumber;
    collateralPayout: BigNumber;
    debtAmount: BigNumber;
    vaultId: BigNumber;
  }
>;

export type VaultLiquidatedEventFilter = TypedEventFilter<VaultLiquidatedEvent>;

export type VaultOpenedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { accountOwner: string; vaultId: BigNumber; vaultType: BigNumber }
>;

export type VaultOpenedEventFilter = TypedEventFilter<VaultOpenedEvent>;

export type VaultSettledEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber],
  {
    accountOwner: string;
    oTokenAddress: string;
    to: string;
    payout: BigNumber;
    vaultId: BigNumber;
    vaultType: BigNumber;
  }
>;

export type VaultSettledEventFilter = TypedEventFilter<VaultSettledEvent>;

export interface Controller extends BaseContract {
  contractName: "Controller";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addressbook(overrides?: CallOverrides): Promise<[string]>;

    calculator(overrides?: CallOverrides): Promise<[string]>;

    callRestricted(overrides?: CallOverrides): Promise<[boolean]>;

    canSettleAssets(
      _underlying: string,
      _strike: string,
      _collateral: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    donate(
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fullPauser(overrides?: CallOverrides): Promise<[string]>;

    getAccountVaultCounter(
      _accountOwner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getConfiguration(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string]>;

    getNakedCap(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getNakedPoolBalance(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPayout(
      _otoken: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getProceed(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVault(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[MarginVault.VaultStructOutput]>;

    getVaultWithDetails(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[MarginVault.VaultStructOutput, BigNumber, BigNumber]>;

    hasExpired(_otoken: string, overrides?: CallOverrides): Promise<[boolean]>;

    initialize(
      _addressBook: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isLiquidatable(
      _owner: string,
      _vaultId: BigNumberish,
      _roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber, BigNumber]>;

    isOperator(
      _owner: string,
      _operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSettlementAllowed(
      _otoken: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    operate(
      _actions: Actions.ActionArgsStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    partialPauser(overrides?: CallOverrides): Promise<[string]>;

    pool(overrides?: CallOverrides): Promise<[string]>;

    refreshConfiguration(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCallRestriction(
      _isRestricted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFullPauser(
      _fullPauser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNakedCap(
      _collateral: string,
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOperator(
      _operator: string,
      _isOperator: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPartialPauser(
      _partialPauser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSystemFullyPaused(
      _fullyPaused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSystemPartiallyPaused(
      _partiallyPaused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sync(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    systemFullyPaused(overrides?: CallOverrides): Promise<[boolean]>;

    systemPartiallyPaused(overrides?: CallOverrides): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    whitelist(overrides?: CallOverrides): Promise<[string]>;
  };

  addressbook(overrides?: CallOverrides): Promise<string>;

  calculator(overrides?: CallOverrides): Promise<string>;

  callRestricted(overrides?: CallOverrides): Promise<boolean>;

  canSettleAssets(
    _underlying: string,
    _strike: string,
    _collateral: string,
    _expiry: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  donate(
    _asset: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fullPauser(overrides?: CallOverrides): Promise<string>;

  getAccountVaultCounter(
    _accountOwner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getConfiguration(
    overrides?: CallOverrides
  ): Promise<[string, string, string, string]>;

  getNakedCap(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  getNakedPoolBalance(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPayout(
    _otoken: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getProceed(
    _owner: string,
    _vaultId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVault(
    _owner: string,
    _vaultId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<MarginVault.VaultStructOutput>;

  getVaultWithDetails(
    _owner: string,
    _vaultId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[MarginVault.VaultStructOutput, BigNumber, BigNumber]>;

  hasExpired(_otoken: string, overrides?: CallOverrides): Promise<boolean>;

  initialize(
    _addressBook: string,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isLiquidatable(
    _owner: string,
    _vaultId: BigNumberish,
    _roundId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber, BigNumber]>;

  isOperator(
    _owner: string,
    _operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSettlementAllowed(
    _otoken: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  operate(
    _actions: Actions.ActionArgsStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  partialPauser(overrides?: CallOverrides): Promise<string>;

  pool(overrides?: CallOverrides): Promise<string>;

  refreshConfiguration(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCallRestriction(
    _isRestricted: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFullPauser(
    _fullPauser: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNakedCap(
    _collateral: string,
    _cap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOperator(
    _operator: string,
    _isOperator: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPartialPauser(
    _partialPauser: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSystemFullyPaused(
    _fullyPaused: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSystemPartiallyPaused(
    _partiallyPaused: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sync(
    _owner: string,
    _vaultId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  systemFullyPaused(overrides?: CallOverrides): Promise<boolean>;

  systemPartiallyPaused(overrides?: CallOverrides): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  whitelist(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addressbook(overrides?: CallOverrides): Promise<string>;

    calculator(overrides?: CallOverrides): Promise<string>;

    callRestricted(overrides?: CallOverrides): Promise<boolean>;

    canSettleAssets(
      _underlying: string,
      _strike: string,
      _collateral: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    donate(
      _asset: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fullPauser(overrides?: CallOverrides): Promise<string>;

    getAccountVaultCounter(
      _accountOwner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfiguration(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string]>;

    getNakedCap(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    getNakedPoolBalance(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPayout(
      _otoken: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProceed(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVault(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<MarginVault.VaultStructOutput>;

    getVaultWithDetails(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[MarginVault.VaultStructOutput, BigNumber, BigNumber]>;

    hasExpired(_otoken: string, overrides?: CallOverrides): Promise<boolean>;

    initialize(
      _addressBook: string,
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isLiquidatable(
      _owner: string,
      _vaultId: BigNumberish,
      _roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber, BigNumber]>;

    isOperator(
      _owner: string,
      _operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSettlementAllowed(
      _otoken: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    operate(
      _actions: Actions.ActionArgsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    partialPauser(overrides?: CallOverrides): Promise<string>;

    pool(overrides?: CallOverrides): Promise<string>;

    refreshConfiguration(overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCallRestriction(
      _isRestricted: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setFullPauser(
      _fullPauser: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setNakedCap(
      _collateral: string,
      _cap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOperator(
      _operator: string,
      _isOperator: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setPartialPauser(
      _partialPauser: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSystemFullyPaused(
      _fullyPaused: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setSystemPartiallyPaused(
      _partiallyPaused: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    sync(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    systemFullyPaused(overrides?: CallOverrides): Promise<boolean>;

    systemPartiallyPaused(overrides?: CallOverrides): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelist(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AccountOperatorUpdated(address,address,bool)"(
      accountOwner?: string | null,
      operator?: string | null,
      isSet?: null
    ): AccountOperatorUpdatedEventFilter;
    AccountOperatorUpdated(
      accountOwner?: string | null,
      operator?: string | null,
      isSet?: null
    ): AccountOperatorUpdatedEventFilter;

    "CallExecuted(address,address,bytes)"(
      from?: string | null,
      to?: string | null,
      data?: null
    ): CallExecutedEventFilter;
    CallExecuted(
      from?: string | null,
      to?: string | null,
      data?: null
    ): CallExecutedEventFilter;

    "CallRestricted(bool)"(isRestricted?: null): CallRestrictedEventFilter;
    CallRestricted(isRestricted?: null): CallRestrictedEventFilter;

    "CollateralAssetDeposited(address,address,address,uint256,uint256)"(
      asset?: string | null,
      accountOwner?: string | null,
      from?: string | null,
      vaultId?: null,
      amount?: null
    ): CollateralAssetDepositedEventFilter;
    CollateralAssetDeposited(
      asset?: string | null,
      accountOwner?: string | null,
      from?: string | null,
      vaultId?: null,
      amount?: null
    ): CollateralAssetDepositedEventFilter;

    "CollateralAssetWithdrawed(address,address,address,uint256,uint256)"(
      asset?: string | null,
      AccountOwner?: string | null,
      to?: string | null,
      vaultId?: null,
      amount?: null
    ): CollateralAssetWithdrawedEventFilter;
    CollateralAssetWithdrawed(
      asset?: string | null,
      AccountOwner?: string | null,
      to?: string | null,
      vaultId?: null,
      amount?: null
    ): CollateralAssetWithdrawedEventFilter;

    "Donated(address,address,uint256)"(
      donator?: string | null,
      asset?: string | null,
      amount?: null
    ): DonatedEventFilter;
    Donated(
      donator?: string | null,
      asset?: string | null,
      amount?: null
    ): DonatedEventFilter;

    "FullPauserUpdated(address,address)"(
      oldFullPauser?: string | null,
      newFullPauser?: string | null
    ): FullPauserUpdatedEventFilter;
    FullPauserUpdated(
      oldFullPauser?: string | null,
      newFullPauser?: string | null
    ): FullPauserUpdatedEventFilter;

    "LongOtokenDeposited(address,address,address,uint256,uint256)"(
      otoken?: string | null,
      accountOwner?: string | null,
      from?: string | null,
      vaultId?: null,
      amount?: null
    ): LongOtokenDepositedEventFilter;
    LongOtokenDeposited(
      otoken?: string | null,
      accountOwner?: string | null,
      from?: string | null,
      vaultId?: null,
      amount?: null
    ): LongOtokenDepositedEventFilter;

    "LongOtokenWithdrawed(address,address,address,uint256,uint256)"(
      otoken?: string | null,
      AccountOwner?: string | null,
      to?: string | null,
      vaultId?: null,
      amount?: null
    ): LongOtokenWithdrawedEventFilter;
    LongOtokenWithdrawed(
      otoken?: string | null,
      AccountOwner?: string | null,
      to?: string | null,
      vaultId?: null,
      amount?: null
    ): LongOtokenWithdrawedEventFilter;

    "NakedCapUpdated(address,uint256)"(
      collateral?: string | null,
      cap?: null
    ): NakedCapUpdatedEventFilter;
    NakedCapUpdated(
      collateral?: string | null,
      cap?: null
    ): NakedCapUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PartialPauserUpdated(address,address)"(
      oldPartialPauser?: string | null,
      newPartialPauser?: string | null
    ): PartialPauserUpdatedEventFilter;
    PartialPauserUpdated(
      oldPartialPauser?: string | null,
      newPartialPauser?: string | null
    ): PartialPauserUpdatedEventFilter;

    "Redeem(address,address,address,address,uint256,uint256)"(
      otoken?: string | null,
      redeemer?: string | null,
      receiver?: string | null,
      collateralAsset?: null,
      otokenBurned?: null,
      payout?: null
    ): RedeemEventFilter;
    Redeem(
      otoken?: string | null,
      redeemer?: string | null,
      receiver?: string | null,
      collateralAsset?: null,
      otokenBurned?: null,
      payout?: null
    ): RedeemEventFilter;

    "ShortOtokenBurned(address,address,address,uint256,uint256)"(
      otoken?: string | null,
      AccountOwner?: string | null,
      from?: string | null,
      vaultId?: null,
      amount?: null
    ): ShortOtokenBurnedEventFilter;
    ShortOtokenBurned(
      otoken?: string | null,
      AccountOwner?: string | null,
      from?: string | null,
      vaultId?: null,
      amount?: null
    ): ShortOtokenBurnedEventFilter;

    "ShortOtokenMinted(address,address,address,uint256,uint256)"(
      otoken?: string | null,
      AccountOwner?: string | null,
      to?: string | null,
      vaultId?: null,
      amount?: null
    ): ShortOtokenMintedEventFilter;
    ShortOtokenMinted(
      otoken?: string | null,
      AccountOwner?: string | null,
      to?: string | null,
      vaultId?: null,
      amount?: null
    ): ShortOtokenMintedEventFilter;

    "SystemFullyPaused(bool)"(isPaused?: null): SystemFullyPausedEventFilter;
    SystemFullyPaused(isPaused?: null): SystemFullyPausedEventFilter;

    "SystemPartiallyPaused(bool)"(
      isPaused?: null
    ): SystemPartiallyPausedEventFilter;
    SystemPartiallyPaused(isPaused?: null): SystemPartiallyPausedEventFilter;

    "VaultLiquidated(address,address,address,uint256,uint256,uint256,uint256,uint256)"(
      liquidator?: string | null,
      receiver?: string | null,
      vaultOwner?: string | null,
      auctionPrice?: null,
      auctionStartingRound?: null,
      collateralPayout?: null,
      debtAmount?: null,
      vaultId?: null
    ): VaultLiquidatedEventFilter;
    VaultLiquidated(
      liquidator?: string | null,
      receiver?: string | null,
      vaultOwner?: string | null,
      auctionPrice?: null,
      auctionStartingRound?: null,
      collateralPayout?: null,
      debtAmount?: null,
      vaultId?: null
    ): VaultLiquidatedEventFilter;

    "VaultOpened(address,uint256,uint256)"(
      accountOwner?: string | null,
      vaultId?: null,
      vaultType?: BigNumberish | null
    ): VaultOpenedEventFilter;
    VaultOpened(
      accountOwner?: string | null,
      vaultId?: null,
      vaultType?: BigNumberish | null
    ): VaultOpenedEventFilter;

    "VaultSettled(address,address,address,uint256,uint256,uint256)"(
      accountOwner?: string | null,
      oTokenAddress?: string | null,
      to?: null,
      payout?: null,
      vaultId?: null,
      vaultType?: BigNumberish | null
    ): VaultSettledEventFilter;
    VaultSettled(
      accountOwner?: string | null,
      oTokenAddress?: string | null,
      to?: null,
      payout?: null,
      vaultId?: null,
      vaultType?: BigNumberish | null
    ): VaultSettledEventFilter;
  };

  estimateGas: {
    addressbook(overrides?: CallOverrides): Promise<BigNumber>;

    calculator(overrides?: CallOverrides): Promise<BigNumber>;

    callRestricted(overrides?: CallOverrides): Promise<BigNumber>;

    canSettleAssets(
      _underlying: string,
      _strike: string,
      _collateral: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donate(
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fullPauser(overrides?: CallOverrides): Promise<BigNumber>;

    getAccountVaultCounter(
      _accountOwner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getNakedCap(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    getNakedPoolBalance(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPayout(
      _otoken: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProceed(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVault(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultWithDetails(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasExpired(_otoken: string, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _addressBook: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isLiquidatable(
      _owner: string,
      _vaultId: BigNumberish,
      _roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOperator(
      _owner: string,
      _operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSettlementAllowed(
      _otoken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    operate(
      _actions: Actions.ActionArgsStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    partialPauser(overrides?: CallOverrides): Promise<BigNumber>;

    pool(overrides?: CallOverrides): Promise<BigNumber>;

    refreshConfiguration(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCallRestriction(
      _isRestricted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFullPauser(
      _fullPauser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNakedCap(
      _collateral: string,
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOperator(
      _operator: string,
      _isOperator: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPartialPauser(
      _partialPauser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSystemFullyPaused(
      _fullyPaused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSystemPartiallyPaused(
      _partiallyPaused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sync(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    systemFullyPaused(overrides?: CallOverrides): Promise<BigNumber>;

    systemPartiallyPaused(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    whitelist(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addressbook(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    callRestricted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    canSettleAssets(
      _underlying: string,
      _strike: string,
      _collateral: string,
      _expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    donate(
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fullPauser(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccountVaultCounter(
      _accountOwner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfiguration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNakedCap(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNakedPoolBalance(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPayout(
      _otoken: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProceed(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVault(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultWithDetails(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasExpired(
      _otoken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _addressBook: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isLiquidatable(
      _owner: string,
      _vaultId: BigNumberish,
      _roundId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOperator(
      _owner: string,
      _operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSettlementAllowed(
      _otoken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    operate(
      _actions: Actions.ActionArgsStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    partialPauser(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    refreshConfiguration(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCallRestriction(
      _isRestricted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFullPauser(
      _fullPauser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNakedCap(
      _collateral: string,
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOperator(
      _operator: string,
      _isOperator: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPartialPauser(
      _partialPauser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSystemFullyPaused(
      _fullyPaused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSystemPartiallyPaused(
      _partiallyPaused: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sync(
      _owner: string,
      _vaultId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    systemFullyPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    systemPartiallyPaused(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    whitelist(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
