/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AddressBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressBook__factory>;
    getContractFactory(
      name: "Controller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Controller__factory>;
    getContractFactory(
      name: "MarginCalculator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MarginCalculator__factory>;
    getContractFactory(
      name: "MarginPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MarginPool__factory>;
    getContractFactory(
      name: "Oracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Oracle__factory>;
    getContractFactory(
      name: "Otoken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Otoken__factory>;
    getContractFactory(
      name: "OtokenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OtokenFactory__factory>;
    getContractFactory(
      name: "Whitelist",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Whitelist__factory>;
    getContractFactory(
      name: "PermitCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PermitCallee__factory>;
    getContractFactory(
      name: "WETH9",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WETH9__factory>;
    getContractFactory(
      name: "PayableProxyController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PayableProxyController__factory>;
    getContractFactory(
      name: "AddressBookInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressBookInterface__factory>;
    getContractFactory(
      name: "AggregatorInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AggregatorInterface__factory>;
    getContractFactory(
      name: "CalleeInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CalleeInterface__factory>;
    getContractFactory(
      name: "CTokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CTokenInterface__factory>;
    getContractFactory(
      name: "ERC20Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Interface__factory>;
    getContractFactory(
      name: "MarginCalculatorInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MarginCalculatorInterface__factory>;
    getContractFactory(
      name: "MarginPoolInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MarginPoolInterface__factory>;
    getContractFactory(
      name: "OpynPricerInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OpynPricerInterface__factory>;
    getContractFactory(
      name: "OracleInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OracleInterface__factory>;
    getContractFactory(
      name: "OtokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OtokenInterface__factory>;
    getContractFactory(
      name: "WETH9Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WETH9Interface__factory>;
    getContractFactory(
      name: "WhitelistInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WhitelistInterface__factory>;
    getContractFactory(
      name: "WSTETHInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WSTETHInterface__factory>;
    getContractFactory(
      name: "YearnVaultInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YearnVaultInterface__factory>;
    getContractFactory(
      name: "ZeroXExchangeInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZeroXExchangeInterface__factory>;
    getContractFactory(
      name: "Migrations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Migrations__factory>;
    getContractFactory(
      name: "Mock0xERC20Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Mock0xERC20Proxy__factory>;
    getContractFactory(
      name: "Mock0xExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Mock0xExchange__factory>;
    getContractFactory(
      name: "MockAddressBook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAddressBook__factory>;
    getContractFactory(
      name: "MockChainlinkAggregator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockChainlinkAggregator__factory>;
    getContractFactory(
      name: "MockController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockController__factory>;
    getContractFactory(
      name: "MockCToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCToken__factory>;
    getContractFactory(
      name: "MockCUSDC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCUSDC__factory>;
    getContractFactory(
      name: "MockDumbERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDumbERC20__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockOracle__factory>;
    getContractFactory(
      name: "MockOtoken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockOtoken__factory>;
    getContractFactory(
      name: "MockPermitERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockPermitERC20__factory>;
    getContractFactory(
      name: "MockPricer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockPricer__factory>;
    getContractFactory(
      name: "MockWhitelistModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockWhitelistModule__factory>;
    getContractFactory(
      name: "MockWSTETHToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockWSTETHToken__factory>;
    getContractFactory(
      name: "MockYToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockYToken__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20PermitUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20PermitUpgradeable__factory>;
    getContractFactory(
      name: "IERC20PermitUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20PermitUpgradeable__factory>;
    getContractFactory(
      name: "ERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Upgradeable__factory>;
    getContractFactory(
      name: "IERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Upgradeable__factory>;
    getContractFactory(
      name: "OwnableUpgradeSafe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeSafe__factory>;
    getContractFactory(
      name: "OwnedUpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnedUpgradeabilityProxy__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "UpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeabilityProxy__factory>;
    getContractFactory(
      name: "Spawn",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Spawn__factory>;
    getContractFactory(
      name: "ChainLinkPricer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ChainLinkPricer__factory>;
    getContractFactory(
      name: "CompoundPricer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CompoundPricer__factory>;
    getContractFactory(
      name: "WstethPricer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WstethPricer__factory>;
    getContractFactory(
      name: "YearnPricer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YearnPricer__factory>;
    getContractFactory(
      name: "ActionTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ActionTester__factory>;
    getContractFactory(
      name: "CalculatorTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CalculatorTester__factory>;
    getContractFactory(
      name: "CalleeAllowanceTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CalleeAllowanceTester__factory>;
    getContractFactory(
      name: "CallTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallTester__factory>;
    getContractFactory(
      name: "FixedPointInt256Tester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedPointInt256Tester__factory>;
    getContractFactory(
      name: "FlashUnwrap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FlashUnwrap__factory>;
    getContractFactory(
      name: "MarginVaultTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MarginVaultTester__factory>;
    getContractFactory(
      name: "OtokenImplV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OtokenImplV1__factory>;
    getContractFactory(
      name: "SignedConverterTester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignedConverterTester__factory>;
    getContractFactory(
      name: "UpgradeableContractV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeableContractV1__factory>;
    getContractFactory(
      name: "UpgradeableContractV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeableContractV2__factory>;

    getContractAt(
      name: "AddressBook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressBook>;
    getContractAt(
      name: "Controller",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Controller>;
    getContractAt(
      name: "MarginCalculator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MarginCalculator>;
    getContractAt(
      name: "MarginPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MarginPool>;
    getContractAt(
      name: "Oracle",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Oracle>;
    getContractAt(
      name: "Otoken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Otoken>;
    getContractAt(
      name: "OtokenFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OtokenFactory>;
    getContractAt(
      name: "Whitelist",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Whitelist>;
    getContractAt(
      name: "PermitCallee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PermitCallee>;
    getContractAt(
      name: "WETH9",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WETH9>;
    getContractAt(
      name: "PayableProxyController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PayableProxyController>;
    getContractAt(
      name: "AddressBookInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressBookInterface>;
    getContractAt(
      name: "AggregatorInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AggregatorInterface>;
    getContractAt(
      name: "CalleeInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CalleeInterface>;
    getContractAt(
      name: "CTokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CTokenInterface>;
    getContractAt(
      name: "ERC20Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Interface>;
    getContractAt(
      name: "MarginCalculatorInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MarginCalculatorInterface>;
    getContractAt(
      name: "MarginPoolInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MarginPoolInterface>;
    getContractAt(
      name: "OpynPricerInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OpynPricerInterface>;
    getContractAt(
      name: "OracleInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OracleInterface>;
    getContractAt(
      name: "OtokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OtokenInterface>;
    getContractAt(
      name: "WETH9Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WETH9Interface>;
    getContractAt(
      name: "WhitelistInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WhitelistInterface>;
    getContractAt(
      name: "WSTETHInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WSTETHInterface>;
    getContractAt(
      name: "YearnVaultInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.YearnVaultInterface>;
    getContractAt(
      name: "ZeroXExchangeInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZeroXExchangeInterface>;
    getContractAt(
      name: "Migrations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Migrations>;
    getContractAt(
      name: "Mock0xERC20Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Mock0xERC20Proxy>;
    getContractAt(
      name: "Mock0xExchange",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Mock0xExchange>;
    getContractAt(
      name: "MockAddressBook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAddressBook>;
    getContractAt(
      name: "MockChainlinkAggregator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockChainlinkAggregator>;
    getContractAt(
      name: "MockController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockController>;
    getContractAt(
      name: "MockCToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCToken>;
    getContractAt(
      name: "MockCUSDC",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCUSDC>;
    getContractAt(
      name: "MockDumbERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDumbERC20>;
    getContractAt(
      name: "MockERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockOracle",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockOracle>;
    getContractAt(
      name: "MockOtoken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockOtoken>;
    getContractAt(
      name: "MockPermitERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockPermitERC20>;
    getContractAt(
      name: "MockPricer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockPricer>;
    getContractAt(
      name: "MockWhitelistModule",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockWhitelistModule>;
    getContractAt(
      name: "MockWSTETHToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockWSTETHToken>;
    getContractAt(
      name: "MockYToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockYToken>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20PermitUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20PermitUpgradeable>;
    getContractAt(
      name: "IERC20PermitUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20PermitUpgradeable>;
    getContractAt(
      name: "ERC20Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Upgradeable>;
    getContractAt(
      name: "IERC20Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Upgradeable>;
    getContractAt(
      name: "OwnableUpgradeSafe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeSafe>;
    getContractAt(
      name: "OwnedUpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnedUpgradeabilityProxy>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "UpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeabilityProxy>;
    getContractAt(
      name: "Spawn",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Spawn>;
    getContractAt(
      name: "ChainLinkPricer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ChainLinkPricer>;
    getContractAt(
      name: "CompoundPricer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CompoundPricer>;
    getContractAt(
      name: "WstethPricer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WstethPricer>;
    getContractAt(
      name: "YearnPricer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.YearnPricer>;
    getContractAt(
      name: "ActionTester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ActionTester>;
    getContractAt(
      name: "CalculatorTester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CalculatorTester>;
    getContractAt(
      name: "CalleeAllowanceTester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CalleeAllowanceTester>;
    getContractAt(
      name: "CallTester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CallTester>;
    getContractAt(
      name: "FixedPointInt256Tester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedPointInt256Tester>;
    getContractAt(
      name: "FlashUnwrap",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FlashUnwrap>;
    getContractAt(
      name: "MarginVaultTester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MarginVaultTester>;
    getContractAt(
      name: "OtokenImplV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OtokenImplV1>;
    getContractAt(
      name: "SignedConverterTester",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SignedConverterTester>;
    getContractAt(
      name: "UpgradeableContractV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeableContractV1>;
    getContractAt(
      name: "UpgradeableContractV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeableContractV2>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
